# Coinflip Config

# MongoDB Connection Creds.
uri: "mongodb+srv://hex:4x2GBPhA0p7KwwZa@legitzxdevelopment-fbwir.mongodb.net/odysseymc?retryWrites=true&w=majority"
database: "odysseymc"
collection: "coinflip"

# Server name
server.name: "OdysseyMC"
cooldown: 10

# Bet Limits
coinflip.min: 10000
coinflip.max: 1000000000
